### ISSUE TITLE
Parameter Expansion (variables), basic support

### ISSUE THREAD

**Issue by KernelDeimos** [HeyPuter/phoenix#13]
### subtasks
- [ ] Parser support for assignment (`name=value`)
- [ ] Parser support for parameter expansion (`$name` and `${name}`)
- [ ] Stack for variables (when executing scripts or using `local`[^1])
- [ ] Update `Token:resolve()` in `Pipeline.js`

[^1]: `local` keyword itself is not in the scope of this task
